import './globals.css'
import { Lato } from 'next/font/google'
import NavBar from '@/components/NavBar'

export const metadata = {
  title: 'ZARA A.Ş.',
  description: 'Generated by create next app',
}

const lato = Lato({ subsets: ['latin'], weight: ['400']})

export default function RootLayout({ children }) {
  return (
    <html lang="tr" className={lato.className}>
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
